### PR TITLE
Update AEON tutorials for version 1.0

### PR DESCRIPTION
**Pull request by daemontus**
*Work in progress: I still need to update one notebook and then check validation, but I could not build the image locally, so I'm using your CI to make the image that I can test with.*

Updates the AEON tutorial notebooks, mostly using new method and argument names that are now planned for long-term support.

The image can be tested using
```
colomoto-docker -V pr<PULL REQUEST ID>
```

### CODE REVIEW

**Comment by daemontus** [comment]
Hi @pauleve! I am again having problems with building the image locally. However, the notebooks should be updated, only some of the cell output is not re-computed (I wanted to do that using the actual image so that I don't have to figure out how to install biolqm locally without conda). Is that something that you can do? (or at least make the image available through dockerhub so that I can update the cell outputs?)

**Comment by pauleve** [comment]
Thanks! 
I've updated the notebooks, removed the .bdd and .pickle files (they do not seem necessary to run the notebooks).
To build and run locally, you can try using:
```
./hooks/build
colomoto-docker -V local --bind .
```
Alternatively, I just update the CI so an image :for-next gets uploaded before validation (which is necessary for uploading the :next.
So in the future, doing `colomoto-docker -V for-next --bind .` should be enough to fix the notebooks from the failing image.

I'll close the PR once the tests passed. Thanks again!

**Comment by daemontus** [comment]
I've tried the local build through `./builds/hooks` on my Debian desktop, but it fails with a mysterious "exit code 4" error, see attached output (the .deb download seems to be ok, but I guess it fails somewhere during the installation?). I tried to download the package and install it normally, and that works. So I'm a bit confused as to what is going on. 

[output.txt](https://github.com/user-attachments/files/17072655/output.txt)

**Comment by daemontus** [comment]
Also... I've split the problematic command in the `Dockerfile` into the individual sub-commands and now it just... works? Maybe the build cache is not transferrable between different versions of docker or the underlying OS?

**Comment by daemontus** [comment]
Next issue: It's trying to connect to `https://conda.anaconda.org/colomoto/label/fake/noarch/repodata.json` due to `conda config --add channels colomoto/label/fake`, but that's failing (the url does not exist?). What is supposed to happen there? Should I replace the fake label with something else?

**Comment by pauleve** [comment]
It could be due to some security layer that limit access to internet (in your output.txt, wget fails with error code 4, which means "Network failure". Maybe adding `--network=host` to the docker build ? Restarting the docker service might help as well... Or are you behind a proxy?

**Comment by pauleve** [comment]
(`docker info` and `docker network ls` may also provide information on potential strange setting)

**Comment by daemontus** [comment]
Thank you! I'll see what I can do. I use this machine to build and host a bunch of other docker containers with jupyter notebooks and network access works fine in those, so hopefully the "global" config should not be completely broken. But it might be some weird docker magic with this particular base image...

**Comment by daemontus** [comment]
Adding `--network=host` to the build command apparently fixes my problems :) Interesting, I never had to add it when building the other containers. But at least now everything seems to be working, so thank you!

**Pull request closed without merging**
