### PR TITLE
Switch to Python 3.8

### PR DESCRIPTION
**Pull request by pauleve**
The image can be tested using
```
colomoto-docker -V pr55
```

### CODE REVIEW

**Comment by pauleve** [comment]
There is an issue with most colomoto conda packages, which for some reason have an explicit dependency on python 3.7 (`python_abi 3.7.* *_cp37m`)

**Comment by pauleve** [comment]
Broken packages to fix:
- [ ] colomoto_jupyter
- [ ] ginsim-python
- [x] mpbn

**Comment by pauleve** [comment]
the package `mpbn` on anaconda is python-abi free, but if I generate it again, the abi is again pulled, as for the other packages.. this might have to do with a dependency...

**Comment by pauleve** [comment]
The channel `defaults` has to be specified first (`conda build -c defaults ..`); see https://github.com/colomoto/colomoto-conda/commit/934840bcb82decf1ab2563b74983072e4513aa74
@aurelien-naldi can you fix casq as well?

**Comment by aurelien-naldi** [comment]
The new CaSQ build is fixed, and included in the Dockerfile in the "for-next" branch

**Pull request merged**
