### PR TITLE
Update AEON.py

### PR DESCRIPTION
**Pull request by daemontus**
This PR which update AEON.py inside colomoto to version [`0.2.0`](https://github.com/sybila/biodivine-aeon-py/releases/tag/0.2.0).

There are a few minor breaking changes, as such I am also attaching up to date versions of each notebook. Hopefully, this should also resolve any compatibility problems with newer Python versions.

### CODE REVIEW

**Comment by pauleve** [comment]
Thanks! Do you think you can also provide packages for python 3.10? For now, many packages are stuck to 3.10...

**Comment by daemontus** [comment]
Working on [it](https://github.com/sybila/biodivine-aeon-py/commit/9fba8ef4b7eb0029b4cda1e79f07a6de88b3a195). Should be online shortly :)

I will then update this PR to be compatible with 3.9 (hopefully, the CI will pass then) and you can switch to 3.10/3.11 at your convenience.

**Comment by pauleve** [comment]
Perfect, thanks!

**Comment by pauleve** [comment]
The notebook complains about cellcollective module not imported, can you have a look?
Also, it is a good idea to include the cellcollective-xxxx.sbml file in the tutorial folder so the tests do not fail when cellcollective is down.. :-)

**Comment by daemontus** [comment]
My bad... I was actually testing using the local .sbml file (it is included) because I had a problem running cell collective and I forgot to uncomment the import back...

I made a fix in my fork... but the PR does not seem to be updating? I don't know why :D Usually it just updates automatically... seems like some kind of Github bug, because otherwise everything else tells me there should be 5 commits here, only this PR thread displays 4... If it does not sync up in a few minutes, I'll just close this and open a new one I guess...

**Comment by daemontus** [comment]
Ok, it's been 15 minutes... I'll just try reopen the PR...

**Pull request closed without merging**
