### PR TITLE
Switch to Python 3.9

### PR DESCRIPTION
**Pull request by pauleve**
The image can be tested using
```
colomoto-docker -V pr87
```

### CODE REVIEW

**Comment by pauleve** [comment]
@vincent-noel we need cmaboss packaged for python 3.9 :smile:

**Comment by vincent-noel** [comment]
I'm on it

**Comment by vincent-noel** [comment]
Should be working, keep me in touch

**Comment by pauleve** [comment]
Wahou, thanks :-)

**Pull request merged**
